[package]
name = "serverlib"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
common   = { workspace = true }
security = { workspace = true }
serde    = { workspace = true }
bincode  = { workspace = true }
log      = { workspace = true }
chrono   = { workspace = true }
openssl  = { workspace = true }
sqlparser = "0.51"
regex     = "1.13.1"
ahash     = "0.8"
flate2    = "1"