[package]
name = "client"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
clientlib  = { workspace = true }
tokio      = { workspace = true, features = ["rt-multi-thread"] }
log        = { workspace = true }
env_logger = { workspace = true }