[package]
name = "clientlib"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
connector  = { workspace = true }
peerlib    = { workspace = true, features = ["connector-stack"] }
common     = { workspace = true }
tokio      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
