CREATE TABLE `__person` (
  `uid` varchar(34) NOT NULL,
  `id_organization` varchar(34) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `id_referer` varchar(34) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `invite_code` varchar(34) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `display_as` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `level` enum('regular','premium','exclusive') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'regular',
  `provider` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'native',
  `mode` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'personal',
  `lang` varchar(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'en',
  `data_store` enum('eu','us','uk','other') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'eu',
  `profile` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `date_created` bigint NOT NULL DEFAULT '0',
  `date_updated` bigint NOT NULL DEFAULT '0',
  `date_ofbirth` bigint NOT NULL DEFAULT '0',
  `image_data` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `is_verified` tinyint unsigned NOT NULL DEFAULT '0',
  `is_private` tinyint unsigned NOT NULL DEFAULT '0',
  `is_setup` tinyint unsigned NOT NULL DEFAULT '1',
  `is_blocked` tinyint unsigned NOT NULL DEFAULT '0',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`),
  KEY `acc_login` (`uid`),
  KEY `is_deleted` (`is_deleted`),
  KEY `signupcode` (`invite_code`),
  KEY `id_referer` (`id_referer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;