[workspace]
resolver = "2"
members = [
    "client",
    "clientlib",
    "common",
    "connector",
    "console",
    "peerlib",
    "security",
    "server",
    "serverlib",
    "tlsserver",
]

[workspace.dependencies]
# Internal crates
common    = { path = "common" }
connector = { path = "connector" }
peerlib   = { path = "peerlib", default-features = false }
security  = { path = "security" }
serverlib = { path = "serverlib" }
tlsserver = { path = "tlsserver" }
clientlib = { path = "clientlib" }

# External
serde               = { version = "1.0.229", features = ["derive"] }
serde_json          = "1"
bincode             = "1.3.2"
log                 = "0.4"
env_logger          = "0.11"
chrono              = "*"
openssl             = "*"
tokio               = { version = "1", features = ["macros", "rt", "sync", "time"] }
rustls              = { version = "0.23", default-features = false, features = ["logging", "std", "tls12", "ring"] }
rustls-pemfile      = "2"
rustls-native-certs = "0.8"
tokio-rustls        = { version = "0.26", default-features = false, features = ["logging", "tls12", "ring"] }


[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage,coverage_nightly)',
] }

[workspace.lints.clippy]
# `clippy::all` is already on by default. It implies the following:
#   * clippy::correctness code that is outright wrong or useless
#   * clippy::suspicious code that is most likely wrong or useless
#   * clippy::complexity code that does something simple but in a complex way
#   * clippy::perf code that can be written to run faster
#   * clippy::style code that should be written in a more idiomatic way
all = { level = "warn", priority = -1 }

# > clippy::pedantic lints which are rather strict or might have false positives
pedantic = { level = "warn", priority = -1 }

# > new lints that are still under development
# (so "nursery" doesn't mean "Rust newbies")
nursery = { level = "warn", priority = -1 }

# > The clippy::cargo group gives you suggestions on how to improve your Cargo.toml file.
# > This might be especially interesting if you want to publish your crate and are not sure
# > if you have all useful information in your Cargo.toml.
cargo = { level = "warn", priority = -1 }

# > The clippy::restriction group will restrict you in some way.
# > If you enable a restriction lint for your crate it is recommended to also fix code that
# > this lint triggers on. However, those lints are really strict by design and you might want
# > to #[expect] them in some special cases, with a comment justifying that.
restriction = { level = "warn", priority = -1 }

blanket_clippy_restriction_lints = "allow"
