[package]
name = "peerlib"
version = "0.1.0"
edition = "2024"

[lints] 
workspace = true

[features]
default = ["connector-stack"]
connector-stack = []
server-p2p = []

[dependencies]
connector           = { workspace = true }
common              = { workspace = true }
security            = { workspace = true }
serde               = { workspace = true }
bincode             = { workspace = true }
log                 = { workspace = true }
rustls              = { workspace = true }
rustls-pemfile      = { workspace = true }
rustls-native-certs = { workspace = true }
sha2        = "0.10"
x509-parser = "0.16"

[dev-dependencies]
rcgen = { version = "0.13", features = ["x509-parser"] }
