[package]
name = "security"
version = "0.1.0"
edition = "2024"

[lints] 
workspace = true

[dependencies]
common         = { workspace = true }
tokio          = { workspace = true, features = ["net", "io-util"] }
tokio-rustls   = { workspace = true }
rustls         = { workspace = true }
rustls-pemfile = { workspace = true }
openssl        = { workspace = true }
rcgen = { version = "0.13", features = ["x509-parser"] }
