[package]
name = "tlsserver"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
security   = { workspace = true }
bincode    = { workspace = true }
env_logger = { workspace = true }
log        = { workspace = true }
serde      = { workspace = true }
