[package]
name = "server"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
serverlib     = { workspace = true }
connector     = { workspace = true }
peerlib       = { workspace = true, features = ["server-p2p"] }
common        = { workspace = true }
security      = { workspace = true }
tlsserver     = { workspace = true }
log           = { workspace = true }
env_logger    = { workspace = true }
bincode       = { workspace = true }
tokio         = { workspace = true, features = ["rt-multi-thread", "signal", "net", "io-util"] }
tokio-rustls  = { workspace = true }
rustls        = { workspace = true }
rustls-pemfile = { workspace = true }
serde_json    = { workspace = true }
tokio-tungstenite = { version = "0.24", default-features = false, features = ["handshake"] }
futures-util      = "0.3.33"