#!/usr/bin/env bash
set -euo pipefail

TLS_SERVER_ADDR="${TLS_SERVER_ADDR:-127.0.0.1:5443}"
TLS_SANS="${TLS_SANS:-localhost}"

CPU_COUNT="$(getconf _NPROCESSORS_ONLN 2>/dev/null || printf '1')"
export DISTDB_RUNTIME_INDEX_BUILD_WORKERS="${DISTDB_RUNTIME_INDEX_BUILD_WORKERS:-$CPU_COUNT}"
export DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP="${DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP:-1}"
export DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS="${DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS:-1}"
export DISTDB_RUNTIME_INDEX_PARALLEL_BUILD_MIN_ROWS="${DISTDB_RUNTIME_INDEX_PARALLEL_BUILD_MIN_ROWS:-250000}"

cargo build --release
killall server || true
RUST_LOG="${RUST_LOG:-info}" \
RUST_BACKTRACE="${RUST_BACKTRACE:-1}" \
./../target/release/server datadir=./data -- wss=on tls_san="$TLS_SANS" tls_server="$TLS_SERVER_ADDR" &