#!/usr/bin/env bash
set -euo pipefail

TLS_SERVER_ADDR="${TLS_SERVER_ADDR:-127.0.0.1:5443}"
TLS_SANS="${TLS_SANS:-localhost}"

# Unified startup profile switch:
# - minimum: smallest memory footprint for bootstrap/runtime index.
# - throughput (default): favors predictable warm query posture and ingest throughput.
DISTDB_PLATFORM_PROFILE="${DISTDB_PLATFORM_PROFILE:-throughput}"

# Backward compatibility for existing automation.
# DISTDB_ENABLE_LOW_MEMORY_PROFILE=1 -> minimum
# DISTDB_ENABLE_LOW_MEMORY_PROFILE=0 -> throughput
if [[ -n "${DISTDB_ENABLE_LOW_MEMORY_PROFILE:-}" ]]; then
	if [[ "$DISTDB_ENABLE_LOW_MEMORY_PROFILE" == "1" ]]; then
		DISTDB_PLATFORM_PROFILE="minimum"
	else
		DISTDB_PLATFORM_PROFILE="throughput"
	fi
fi

if [[ "$DISTDB_PLATFORM_PROFILE" == "minimum" ]]; then
	export DISTDB_RUNTIME_INDEX_BUILD_WORKERS="${DISTDB_RUNTIME_INDEX_BUILD_WORKERS:-1}"
	export DISTDB_RUNTIME_INDEX_MATERIALIZE_NON_PRIMARY="${DISTDB_RUNTIME_INDEX_MATERIALIZE_NON_PRIMARY:-0}"
	export DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP="${DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP:-0}"
	export DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS="${DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS:-0}"
elif [[ "$DISTDB_PLATFORM_PROFILE" == "throughput" ]]; then
	export DISTDB_RUNTIME_INDEX_BUILD_WORKERS="${DISTDB_RUNTIME_INDEX_BUILD_WORKERS:-4}"
	export DISTDB_RUNTIME_INDEX_MATERIALIZE_NON_PRIMARY="${DISTDB_RUNTIME_INDEX_MATERIALIZE_NON_PRIMARY:-1}"
	export DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP="${DISTDB_RUNTIME_INDEX_PRELOAD_ACCESSORS_ON_BOOTSTRAP:-1}"
	export DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS="${DISTDB_RUNTIME_INDEX_BACKGROUND_PREWARM_SKIPPED_ACCESSORS:-1}"
	export DISTDB_RUNTIME_INDEX_PARALLEL_BUILD_MIN_ROWS="${DISTDB_RUNTIME_INDEX_PARALLEL_BUILD_MIN_ROWS:-250000}"
	export DISTDB_RUNTIME_INDEX_AGGRESSIVE_RESERVE_GROWTH="${DISTDB_RUNTIME_INDEX_AGGRESSIVE_RESERVE_GROWTH:-1}"
else
	echo "unknown DISTDB_PLATFORM_PROFILE='$DISTDB_PLATFORM_PROFILE' (expected: minimum|throughput)" >&2
	exit 2
fi

cargo build --release
killall server || true
./../target/release/server datadir=./data -- wss=on tls_san="$TLS_SANS" tls_server="$TLS_SERVER_ADDR" &