[package]
name = "common"
version = "0.1.0"
edition = "2024"
authors = ["Sam Colak <sam@samcolak.com>"]

[lints] 
workspace = true

[dependencies]
chrono     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
bincode    = { workspace = true }
tokio      = { workspace = true }
openssl    = { workspace = true }
uuid    = { version = "1.24.0", features = ["serde", "v4", "v7", "fast-rng"] }
libp2p  = { version = "0.55.0", default-features = false, features = ["cbor", "identify", "macros", "mdns", "noise", "ping", "quic", "request-response", "serde", "tcp", "tokio", "yamux"] }
md5     = "0.8.0"