[package]
name = "console"
version = "0.1.0"
edition = "2024"

[lints] 
workspace = true

[dependencies]
connector  = { workspace = true }
peerlib    = { workspace = true, features = ["connector-stack"] }
common     = { workspace = true }
env_logger = { workspace = true }
log        = { workspace = true }
rustls     = { workspace = true }
rustyline  = "18.0.0"
